name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Escolha a versão Node.js apropriada

      - name: Install dependencies
        run: npm install --force

      - name: Build React App
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "andytargino@outlook.com"
          git config --global user.name "AndyTargino"
          git checkout --orphan gh-pages
          git rm -rf .
          mv build/* .
          git add .
          git commit -m "Deploy React App to GitHub Pages"
          git branch -M gh-pages
          git remote add origin https://github.com/AndyTargino/Maestro-Chatbot-Flow.git
          git push -f origin gh-pages
